---> customer_revenue_ranking

-- CTE: Calculate total revenue generated by each customer
with customer_revenue as (
	select
		CustomerKey,
		SalesAmount as total_revenue
	from FactInternetSales
	group by
		CustomerKey
),

-- CTE: Rank customers based on total revenue (highest first)
ranked_customers as (
	select
		CustomerKey,
		total_revenue,
		dense_rank() over(
			order by total_revenue desc
		) as revenue_rank
	from customer_revenue
)

-- Final Select: Display customer revenue along with ranking
select
	CustomerKey,
	total_revenue,
	revenue_rank
from ranked_customers
order by revenue_rank;
