---> top_10_percent_customers_pareto

-- CTE: Calculate total revenue generated by each customer
with customer_revenue as (
	select
		CustomerKey,
		sum(SalesAmount) as total_revenue
	from FactInternetSales
	group by CustomerKey
),

-- CTE: Divide customers into 10 revenue deciles (Top 10% = decile 1)
ranked_customers as (
	select
		CustomerKey,
		total_revenue,
		ntile(10) over(order by total_revenue desc) as rev_decile
	from customer_revenue
)

-- Final Select: Retrieve top 10% revenue contributors with full name
select
	rc.CustomerKey,
	dc.FirstName + ' ' + dc.LastName as full_name,
	rc.total_revenue
from ranked_customers rc
join DimCustomer dc
	on rc.CustomerKey = dc.CustomerKey
where rc.rev_decile = 1
order by rc.total_revenue desc;
